version: '3.8'
services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    ports:
      - "1522:1522"
    environment:
      ORACLE_PASSWORD: Admin123

  app:
    build: .
    container_name: ticket-app
    depends_on:
      - oracle-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1522/XEPDB1
      SPRING_DATASOURCE_USERNAME: "sys as sysdba"
      SPRING_DATASOURCE_PASSWORD: Admin123
